# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies without running any scripts
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the TypeScript project
RUN npm run build

FROM node:22-alpine AS release

# Set the working directory inside the container
WORKDIR /app

# Copy only necessary files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install production dependencies
RUN npm ci --ignore-scripts --omit-dev

# Set environment variable for production
ENV NODE_ENV=production

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
